version: 2
jobs:
  build:
    working_directory: ~/circleci
    docker:
      - image: python:latest
        environment:
	  FLASK_CONFIG: testing
	  TEST_DATABASE_URL: postgresql://ubuntu@localhost/circle_test?sslmode=disable
      - image: postgres:latest
	environment: 
	  POSTGRES_USER: ubuntu
	  POSTGRES_DB: circle_test
	  POSTGRES_PASSWORD: ""
      - image: selenium/standalone-chrome:3.1.0
    steps:
      - checkout
      - run: 
	name: Install Python deps in venv
	command: |
	  python3 -m venv venv
	  . venv/bin/activate
	  pip install -r requirements/dev.txt
